/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ABOBIO;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import static ABOBIO.ListMovie.txGenre;
import static ABOBIO.ListMovie.txImage;
import static ABOBIO.ListMovie.txTitle;

/**
 *
 * @author jacks
 */
public class BookingTicket extends javax.swing.JFrame {

    /**
     * Creates new form BookingTicket
     */
    public BookingTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txDate = new javax.swing.JLabel();
        txTime1 = new javax.swing.JButton();
        txTime2 = new javax.swing.JButton();
        txTime3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txDate1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txTime4 = new javax.swing.JButton();
        txTime5 = new javax.swing.JButton();
        txTime6 = new javax.swing.JButton();
        txDate2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txTime7 = new javax.swing.JButton();
        tx31jm5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABOBIO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 28)); // NOI18N
        jLabel1.setText("ABOBIO Ticket Booking Movie");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(645, 645, 645)
                    .addComponent(jLabel3)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        jButton1.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txImage, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        txTitle.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N

        txTime.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Time.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel4.setText("Schedule Movie");

        txDate.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txDate.setText("29-01-2023");

        txTime1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime1.setText("12 : 00");
        txTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime1ActionPerformed(evt);
            }
        });

        txTime2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime2.setText("14 : 00");
        txTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime2ActionPerformed(evt);
            }
        });

        txTime3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime3.setText("16 : 00");
        txTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime3ActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        txDate1.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txDate1.setText("30-01-2023");

        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));

        txTime4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime4.setText("14 : 00");
        txTime4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime4ActionPerformed(evt);
            }
        });

        txTime5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime5.setText("18 : 00");
        txTime5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime5ActionPerformed(evt);
            }
        });

        txTime6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime6.setText("18 : 00");
        txTime6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime6ActionPerformed(evt);
            }
        });

        txDate2.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txDate2.setText("31-01-2023");

        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 20));

        txTime7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTime7.setText("15 : 00");
        txTime7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTime7ActionPerformed(evt);
            }
        });

        tx31jm5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tx31jm5.setText("17 : 00");
        tx31jm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx31jm5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTime))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txTime1)
                        .addGap(18, 18, 18)
                        .addComponent(txTime2)
                        .addGap(18, 18, 18)
                        .addComponent(txTime3)
                        .addGap(18, 18, 18)
                        .addComponent(txTime6))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txTime4)
                        .addGap(18, 18, 18)
                        .addComponent(txTime5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txTime7)
                        .addGap(18, 18, 18)
                        .addComponent(tx31jm5))
                    .addComponent(txDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTime1)
                            .addComponent(txTime2)
                            .addComponent(txTime3)
                            .addComponent(txTime6))
                        .addGap(18, 18, 18)
                        .addComponent(txDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTime4)
                            .addComponent(txTime5))
                        .addGap(18, 18, 18)
                        .addComponent(txDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTime7)
                            .addComponent(tx31jm5)))
                    .addComponent(jButton3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Dashboard a = new Dashboard();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txTime4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime4ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid,md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-30' AND"
            + " s.time = '14:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime4ActionPerformed

    private void txTime7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime7ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-31' AND"
            + " s.time = '15:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime7ActionPerformed

    private void tx31jm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx31jm5ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-31' AND"
            + " s.time = '17:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
             
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_tx31jm5ActionPerformed

    private void txTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-29' AND"
            + " s.time = '12:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime1ActionPerformed

    private void txTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime2ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-29' AND"
            + " s.time = '14:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));  
             Ticket.txTicket.setText(m.getString(5));
            
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime2ActionPerformed

    private void txTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime3ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-29' AND"
            + " s.time = '16:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime3ActionPerformed

    private void txTime6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime6ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time,s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-29' AND"
            + " s.time = '18:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime6ActionPerformed

    private void txTime5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTime5ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT m.title, s.date, s.time, s.scheduleid, md.ticketid FROM moviedetail md JOIN movies m ON m.movieid = md.movieid"
            + " JOIN schedule s ON s.scheduleid = md.scheduleid WHERE Title ='" + txTitle.getText() + "'AND s.date = '2023-01-30' AND"
            + " s.time = '18:00'";
            ResultSet m = s.executeQuery(sql);
            
            if(m.next()){

             ImageIcon icon = new ImageIcon();
             Ticket.txImage.setIcon(txImage.getIcon());
             Ticket.txTitle.setText(m.getString(1));
             Ticket.txDate.setText(m.getString(2));
             Ticket.txTime.setText(m.getString(3));
             Ticket.txSchedule.setText(m.getString(4));
             Ticket.txTicket.setText(m.getString(5));
            
            }

        }catch(SQLException e){
            System.out.println("Error");
        }
        
        this.dispose();
        Ticket t = new Ticket();
        t.setVisible(true);
    }//GEN-LAST:event_txTime5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ListMovie b = new ListMovie();
        b.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/images/Logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-foltxTime     /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton tx31jm5;
    private javax.swing.JLabel txDate;
    private javax.swing.JLabel txDate1;
    private javax.swing.JLabel txDate2;
    public static final javax.swing.JLabel txImage = new javax.swing.JLabel();
    public static final javax.swing.JLabel txTime = new javax.swing.JLabel();
    private javax.swing.JButton txTime1;
    private javax.swing.JButton txTime2;
    private javax.swing.JButton txTime3;
    private javax.swing.JButton txTime4;
    private javax.swing.JButton txTime5;
    private javax.swing.JButton txTime6;
    private javax.swing.JButton txTime7;
    public static final javax.swing.JLabel txTitle = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
